
import = [
"~/.config/alacritty/dream.toml",
"~/.config/alacritty/fonts.toml",
]

live_config_reload = true

[shell]
program = "pwsh"
args = ["-NoLogo"]

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.90

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "On"


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 180
lines = 50

[window.padding]
x = 6
y = 6

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

