[colors.bright]
black = "#395691"
blue = "#6188FF"
cyan = "#5EE7FF"
green = "#4FFFDC"
magenta = "#8A8AFF"
red = "#FF4F9E"
white = "#C4E5FF"
yellow = "#FFD5A1"

[colors.normal]
black = "#1D2C4A"
blue = "#6188FF"
cyan = "#5EE7FF"
green = "#4FFFDC"
magenta = "#8A8AFF"
red = "#FF4F9E"
white = "#C4E5FF"
yellow = "#FFC0A1"

[colors.primary]
background = "#1a2444"
foreground = "#D1EAFF"

[colors.selection]
background = "#6e45ff"
foreground = "#D1EAFF"

[colors.cursor]
text = "#D1EAFF"
cursor = "#6E45FF"