[font]
size = 9

[font.bold]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 2