[font]
size = 9.5

[font.bold]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "Cousine Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4